Repository NOW-SOPT-APP3-PlanFit/PlanFit-Android, pull requests merged in 2024-05, with the labels that each got.

#4 [feat] #2 color system 구현
  app/src/main/res/values/colors.xml
Labels: 기초세팅

#6 [add] #3 icon 추가
  app/src/main/res/drawable/ic_analysis_24.xml
  app/src/main/res/drawable/ic_arrow_bottom_16.xml
  app/src/main/res/drawable/ic_arrow_down_24.xml
  app/src/main/res/drawable/ic_arrow_left_16.xml
  app/src/main/res/drawable/ic_arrow_left_24.xml
  app/src/main/res/drawable/ic_clock_16.xml
  app/src/main/res/drawable/ic_community_24.xml
  app/src/main/res/drawable/ic_delete_24.xml
  app/src/main/res/drawable/ic_dot_big_off_16.xml
  app/src/main/res/drawable/ic_dot_big_on_16.xml
  app/src/main/res/drawable/ic_dumbbell_40.xml
  app/src/main/res/drawable/ic_ellipsis_24.xml
  app/src/main/res/drawable/ic_exchange_16.xml
  app/src/main/res/drawable/ic_exercise_24.xml
  app/src/main/res/drawable/ic_fire_40.xml
  app/src/main/res/drawable/ic_hamburger_24.xml
  app/src/main/res/drawable/ic_headphone_24.xml
  app/src/main/res/drawable/ic_heart_active_16.xml
  app/src/main/res/drawable/ic_heart_inactive_16.xml
  app/src/main/res/drawable/ic_link_16.xml
  app/src/main/res/drawable/ic_list_24.xml
  app/src/main/res/drawable/ic_onair_active_16.xml
  app/src/main/res/drawable/ic_onair_inactive_16.xml
  app/src/main/res/drawable/ic_pause_16.xml
  app/src/main/res/drawable/ic_pause__24.xml
  app/src/main/res/drawable/ic_pencil_16.xml
  app/src/main/res/drawable/ic_play_16.xml
  app/src/main/res/drawable/ic_play__24.xml
  app/src/main/res/drawable/ic_playnext_24.xml
  app/src/main/res/drawable/ic_plus_16.xml
  app/src/main/res/drawable/ic_profile_24.xml
  app/src/main/res/drawable/ic_reverse_24.xml
  app/src/main/res/drawable/ic_set_40.xml
  app/src/main/res/drawable/ic_settings_24.xml
  app/src/main/res/drawable/ic_share_24.xml
  app/src/main/res/drawable/ic_slash_active_16.xml
  app/src/main/res/drawable/ic_slash_done_16.xml
  app/src/main/res/drawable/ic_speaker_24.xml
  app/src/main/res/drawable/ic_tooltip_24.xml
  app/src/main/res/drawable/ic_triangle_16.xml
Labels: 기초세팅

#5 [feat] #1 typography 구현
  app/src/main/res/font/notosan_black.otf
  app/src/main/res/font/notosans_bold.otf
  app/src/main/res/font/notosans_light.otf
  app/src/main/res/font/notosans_medium.otf
  app/src/main/res/font/notosans_regular.otf
  app/src/main/res/font/notosans_thin.otf
  app/src/main/res/values/themes.xml
  app/src/main/res/values/typography.xml
Labels: 기초세팅

#16 Feature/#7 메인 뷰 구현
  app/src/main/res/drawable/btn_ai_72.xml
  app/src/main/res/drawable/btn_premium.xml
  app/src/main/res/drawable/btn_premium_2x.xml
  app/src/main/res/drawable/btn_stamp_active.xml
  app/src/main/res/drawable/btn_stamp_inactive.xml
  app/src/main/res/drawable/ic_exercise_active_24.xml
  app/src/main/res/drawable/ic_line_12.xml
  app/src/main/res/drawable/ic_profile_24.png
  app/src/main/res/drawable/ic_profile_24.xml
  app/src/main/res/drawable/shape_gray_fill_10_rect.xml
  app/src/main/res/drawable/shape_gray_fill_50_rect.xml
  app/src/main/res/drawable/shape_main_fill_12_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_bottom_sheet.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ui

#22 Feature/#21 스트레칭 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/app3/planfit/core/ui/activity/ExerciseMainActivity.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/StretchingMainActivity.kt
  app/src/main/res/drawable/prog_active_bar.xml
  app/src/main/res/layout/activity_stretching_main.xml
Labels: ui, :ribbon: 효은

#20 [feat] #17 운동리스트 뷰 서버연결
  app/build.gradle.kts
  app/src/main/java/org/sopt/app3/planfit/core/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/app3/planfit/data/ApiFactory.kt
  app/src/main/java/org/sopt/app3/planfit/data/api/ExerciseListService.kt
  app/src/main/java/org/sopt/app3/planfit/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/sopt/app3/planfit/data/model/request/RequestPutExercisesIndexDto.kt
  app/src/main/java/org/sopt/app3/planfit/data/model/response/ResponseGetExercisesDto.kt
  app/src/main/java/org/sopt/app3/planfit/data/model/response/base/BaseResponse.kt
  app/src/main/java/org/sopt/app3/planfit/data/repo/ExerciseListRepositoryImpl.kt
  app/src/main/java/org/sopt/app3/planfit/domain/model/Exercise.kt
  app/src/main/java/org/sopt/app3/planfit/domain/model/IndexInfo.kt
  app/src/main/java/org/sopt/app3/planfit/domain/provider/ResourceProvider.kt
  app/src/main/java/org/sopt/app3/planfit/domain/repo/ExerciseListRepository.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciselist/ExerciseListActivity.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciselist/ExerciseViewModel.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciselist/adapter/ExerciseListAdapter.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciselist/callback/ItemMoveCallback.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciselist/viewholder/ExerciseViewHolder.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/provider/ResourceProviderImpl.kt
  app/src/main/res/layout/activity_exercise_list.xml
  app/src/main/res/layout/item_exercise_list_muscle.xml
Labels: :robot: 상욱, 서버 연결

#28 [feat] #15 메인 뷰 바텀시트 구현
  app/build.gradle.kts
  app/src/main/java/org/sopt/app3/planfit/domain/model/ExerciseCondition.kt
  app/src/main/java/org/sopt/app3/planfit/domain/model/ExerciseTime.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/MainActivity.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciseconditionlist/ExerciseConditionBottomSheetFragment.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciseconditionlist/ExerciseConditionListViewModel.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciseconditionlist/adapter/ExerciseConditionListAdapter.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciseconditionlist/viewholder/ExerciseConditionListViewHolder.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisetimelist/ExerciseTimeBottomSheetFragment.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisetimelist/ExerciseTimeListViewModel.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisetimelist/adapter/ExerciseTimeListAdapter.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisetimelist/viewholder/ExerciseTimeListViewHolder.kt
  app/src/main/res/drawable/item_time_list_custom.xml
  app/src/main/res/drawable/main_bottom_sheet_custom.xml
  app/src/main/res/drawable/shape_main_line_10_rect.xml
  app/src/main/res/layout/activity_exercise_main.xml
  app/src/main/res/layout/fragment_exercise_condition_bottom_sheet.xml
  app/src/main/res/layout/fragment_exercise_time_bottom_sheet.xml
  app/src/main/res/layout/item_exercise_condition_list.xml
  app/src/main/res/layout/item_exercise_time_list.xml
  gradle/libs.versions.toml
Labels: ui, :ribbon: 효은

#25 [feat] #23 스트레칭 뷰 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/app3/planfit/presentation/StretchingMainActivity.kt
  app/src/main/res/drawable/gif_exc_cycle.png
  app/src/main/res/drawable/stretching_time_progressbar.xml
  app/src/main/res/layout/activity_stretching_main.xml
Labels: :ribbon: 효은, 기능 구현

#27 [feat] #19 stopwatch ui
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/app3/planfit/data/repo/StopWatchRepoImpl.kt
  app/src/main/java/org/sopt/app3/planfit/domain/repo/StopWatchRepo.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/StopwatchActivity.kt
  app/src/main/res/drawable/ic_dot_small_off_16.xml
  app/src/main/res/drawable/ic_dot_small_on_16.xml
  app/src/main/res/drawable/sel_stopwatch_play.xml
  app/src/main/res/drawable/shape_main_line_10.xml
  app/src/main/res/drawable/shape_main_line_15.xml
  app/src/main/res/layout/activity_exercise_main.xml
  app/src/main/res/layout/activity_stopwatch.xml
  app/src/main/res/layout/item_exercise_main_set_in_progress.xml
Labels: ui, :rabbit: 서희

#30 [Feat] #24 세트 추가, 완료 통신
  app/src/main/java/org/sopt/app3/planfit/core/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/app3/planfit/data/ApiFactory.kt
  app/src/main/java/org/sopt/app3/planfit/data/api/ExerciseMainService.kt
  app/src/main/java/org/sopt/app3/planfit/data/repo/ExerciseMainRepositoryImpl.kt
  app/src/main/java/org/sopt/app3/planfit/domain/repo/ExerciseMainRepository.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/ExerciseMainActivity.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/ExerciseMainViewModel.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/SetViewModel.kt
Labels: :rabbit: 서희, 서버 연결

#32 [feat] #31 좋아요 통신
  app/src/main/java/org/sopt/app3/planfit/core/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/app3/planfit/data/ApiFactory.kt
  app/src/main/java/org/sopt/app3/planfit/data/api/LikeService.kt
  app/src/main/java/org/sopt/app3/planfit/data/repo/LikeRepoImpl.kt
  app/src/main/java/org/sopt/app3/planfit/domain/repo/LikeRepo.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/ExerciseMainActivity.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/LikeViewModel.kt
Labels: :rabbit: 서희, 서버 연결

#35 [feat] #34 마무리 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/app3/planfit/PlanFitApp.kt
  app/src/main/java/org/sopt/app3/planfit/core/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/app3/planfit/data/ApiFactory.kt
  app/src/main/java/org/sopt/app3/planfit/data/model/response/ResponseGetMainDto.kt
  app/src/main/java/org/sopt/app3/planfit/data/repo/MainRepositoryImpl.kt
  app/src/main/java/org/sopt/app3/planfit/domain/repo/MainRepository.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/MainActivity.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/MainViewModel.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/StretchingMainActivity.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/StretchingMainViewModel.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciseconditionlist/ExerciseConditionBottomSheetFragment.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciseconditionlist/adapter/ExerciseConditionListAdapter.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciseconditionlist/viewholder/ExerciseConditionListViewHolder.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exerciselist/ExerciseListActivity.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/ExerciseMainActivity.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisemain/ExerciseMainViewModel.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisetimelist/ExerciseTimeBottomSheetFragment.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisetimelist/ExerciseTimeListViewModel.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisetimelist/adapter/ExerciseTimeListAdapter.kt
  app/src/main/java/org/sopt/app3/planfit/presentation/exercisetimelist/viewholder/ExerciseTimeListViewHolder.kt
  app/src/main/res/layout/activity_exercise_list.xml
  app/src/main/res/layout/activity_exercise_main.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_stretching_main.xml
Labels: :robot: 상욱
